spring:
  application:
    name: Jetbrains-Help
server:
  port: 10768


help:
  # SSL证书信息配置(有证书信息时可访问https,否则只能访问http),证书来源cf,15年有效期
  ssl:
    # 证书路径
    path: /etc/ssl/cloudflare/keystore.p12
    # 证书密码
    password: cf-cert
    # 证书别名
    alias: cloudflare

  # ja-netfilter.zip证书信息配置
  certificate:
    # 是否使用通用证书（true/false）当为false时自动生成新的证书
    common: true

  # 产品信息配置
  product:
    # 是否启用定时刷新任务（true/false）
    refresh-enabled: true
    # 请求超时时间（毫秒）
    timeout: 30000

  # 插件信息获取配置
  plugins:
    # 是否启用定时刷新任务（true/false）
    refresh-enabled: true
    # 分页大小（每次请求获取的插件数量，建议不超过 20）
    page-size: 20
    # 并发线程数（用于并行请求不同页面的插件数据）
    thread-count: 5
    # 请求超时时间（毫秒）
    timeout: 30000